replicaCount: 1

image:
  repository: andersongn/strapi-minikube
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: "strapi-app"
fullnameOverride: "strapi"

serviceAccount:
  create: true
  annotations: {}
  name: "strapi"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: NodePort
  port: 1337

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: strapi.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
